'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class EditCart
    
    '''<summary>
    '''gvCart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvCart As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''FeesAll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FeesAll As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''btnSaveCart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveCart As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnCancEditCart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancEditCart As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnDialogResponseYes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDialogResponseYes As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnDialogResponseNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDialogResponseNo As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''hfDialogID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfDialogID As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''OrigCart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OrigCart As Global.System.Web.UI.WebControls.HiddenField
End Class
