'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class MyTenants
    
    '''<summary>
    '''ErrorMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ErrorMessage As Global.System.Web.UI.WebControls.PlaceHolder
    
    '''<summary>
    '''FailureText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FailureText As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''MainAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MainAddress As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''OwnerName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OwnerName As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''AgentName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AgentName As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''BalAmt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BalAmt As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''UnitNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UnitNo As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''UnitStat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UnitStat As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''InitRent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents InitRent As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''TenStDt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TenStDt As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''HouseServs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HouseServs As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''NumTenants control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NumTenants As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''SmokYN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SmokYN As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''SmokDt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SmokDt As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''PriorEndDt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PriorEndDt As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''TermReason control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TermReason As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''gvTenants control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvTenants As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''btnBack control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBack As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnDialogResponseYes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDialogResponseYes As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnDialogResponseNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDialogResponseNo As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''hfDialogID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfDialogID As Global.System.Web.UI.WebControls.HiddenField
End Class
