'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class UpdateTenancy
    
    '''<summary>
    '''MainAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MainAddress As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''OwnerName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OwnerName As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''AgentName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AgentName As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''BalAmt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BalAmt As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''UnitNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UnitNo As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''UnitStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UnitStatus As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''InitRent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents InitRent As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TenStDt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TenStDt As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''HServs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HServs As Global.System.Web.UI.WebControls.CheckBoxList
    
    '''<summary>
    '''HServsOthr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HServsOthr As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''HServOthrBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HServOthrBox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''NumTenants control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NumTenants As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''RB1Y control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RB1Y As Global.System.Web.UI.HtmlControls.HtmlInputRadioButton
    
    '''<summary>
    '''RB1N control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RB1N As Global.System.Web.UI.HtmlControls.HtmlInputRadioButton
    
    '''<summary>
    '''SmokeDt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SmokeDt As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''PTenDt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PTenDt As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TermReas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TermReas As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''TermDescr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TermDescr As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''gvTenants control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvTenants As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''btnAddTenant control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddTenant As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''AddTenant control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AddTenant As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''NewFirst control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NewFirst As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''NewLast control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NewLast As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''NewPhon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NewPhon As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''NewEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NewEmail As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''SaveNewTen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SaveNewTen As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''CancelNewTen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CancelNewTen As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''chkDeclare control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkDeclare As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''DeclareInits control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DeclareInits As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnUpdTen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnUpdTen As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancel As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnDialogResponseYes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDialogResponseYes As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnDialogResponseNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDialogResponseNo As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''hfDialogID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfDialogID As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hfUnitID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfUnitID As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hfOrigTenStDt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfOrigTenStDt As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hfOwnerEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfOwnerEmail As Global.System.Web.UI.WebControls.HiddenField
End Class
